version: '3.4'
services:
  db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_SERVICE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MARIADB_SERVICE_DEFAULT_DATABASE}
    ports:
      - ${MARIADB_SERVICE_PORT}:3306
    volumes:
      - db:/var/lib/mysql

  user_api:
    depends_on:
      - db
    build:
      context: UserApi
      dockerfile: Dockerfile
    ports:
      - ${USER_API_SERVICE_PORT}:80


volumes:
  db:

